spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-secret-password
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update

